---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: cmcontainer
      image: alpine
      args:
        - sleep
        - 1d
      ports:
        - containerPort: 80
      env:
        - name: MY_VARIABLE
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: my-variable
      volumeMounts:
        - mountPath: /configmap
          name: configmap-volume
  volumes:
    - name: configmap-volume
      configMap:
        name: configmap