---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Deployment
spec:
  selector: 
    matchLabels:
      app: test
  replicas: 2
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: testContainer
          image: bhaskar150/activity:1.0
          ports:
            - containerPort: 80
              protocol: TCP
        
        