---
apiVersion: v1
kind: Pod
metadata:
  name: healthcheck
spec:
  containers:
    - name: nginx
      image: nginx:1.21
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          port: 80
          path: /
        initialDelaySeconds: 5
        periodSeconds: 3
        failureThreshold: 3
        successThreshold: 2
      readinessProbe:
        httpGet:
          port: 80
          path: /
        initialDelaySeconds: 2
        periodSeconds: 3
        failureThreshold: 3
        successThreshold: 2