---
apiVersion: v1
kind: Pod
metadata:
  name: initcontainers
spec:
  containers:
    - name: c1
      image: nginx
      ports:
        - containerPort: 80
  initContainers:
    - name: initc1
      image: alpine
      command: ['sh','-c','sleep 30s']
    - name: initc2
      image: alpine
      command: ['sh','-c','sleep 30s']