---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
spec:
  selector:
    matchLabels:
      app: jenkins
      version: "1.651.2"
  template:
    metadata:
      labels:
        app: jenkins
        version: "1.651.2"
    spec:
      containers:
        - name: rscontainer
          image: jenkins:1.651.2
          ports:
            - containerPort: 8080
              protocol: TCP
  replicas: 2