---
apiVersion: v1
kind: Pod
metadata:
  name: resorcelimits
spec:
  containers:
    - name: nginx
      image: nginx:1.21
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          port: 80
          path: /
        initialDelaySeconds: 5
        periodSeconds: 3
        failureThreshold: 3
        successThreshold: 2
      readinessProbe:
        httpGet:
          port: 80
          path: /
        initialDelaySeconds: 2
        periodSeconds: 3
        failureThreshold: 3
        successThreshold: 2
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"