---
apiVersion: v1
kind: Pod
metadata:
  name: secrets-pod
spec:
  containers:
    - name: secretcontainer
      image: alpine
      command:
        - sleep
        - 1d
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /secrets
          name: secrets_volume
  volumes:
    - name: secrets_volume
      secret:
        secretName: credentials